config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :lessons do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:index]
  end
  resources :bookings, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  get '/profile', to: 'pages#profile', as: 'profile'
  # new controller profile for the
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
  has_one :review, dependent: :destroy

  validates :date, presence: true

  def end_date
    self.date + self.lesson.duration.hours
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons
  has_one_attached :photo
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :category
  belongs_to :user


  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings, dependent: :destroy


  has_one_attached :photo # cloudinary lesson pic for card

  include PgSearch::Model
    pg_search_scope :search_by_name_and_description,
      against: [ :name, :description ],
      associated_against: {
      user: [:name, :bio],
      category: [ :name ],
      },
      using: {
        tsearch: { prefix: true }
      }

  # validates :name, :description, :price, :duration, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :lesson
  has_many :bookings
  has_many :lessons, through: :bookings
  has_many :reviews, through: :lessons
  has_many :reviews, through: :bookings

  has_one_attached :photo #cloudinary profile pic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :bio, :is_mentor, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :name, :bio, :is_mentor, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = []
    if current_user.bookings != nil
      @mentor_bookings = current_user.bookings
      @mentor_bookings.each { |booking| @bookings << booking }
    end

    if current_user.lesson != nil
      @student_bookings = current_user.lesson.bookings
      @student_bookings.each { |booking| @bookings << booking }
    end
  end

  def new
    @lesson = Lesson.find(params[:lesson_id])
    @booking = Booking.new
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @booking = Booking.new(allowed_params)
    @booking.lesson_id = params[:lesson_id]
    @booking.user = current_user
    if is_booked?(@booking)
      if @booking.save
        redirect_to lesson_path(params[:lesson_id])
        flash[:alert] = "Booking successful"
      else
        render 'new'
      end
    else
      flash[:notice] = "The Mentor is already booked for this time"
      render 'new'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def allowed_params
    params.require(:booking).permit(:date)
  end

  def is_booked?(booking)
    booking.lesson.bookings.all? do |check|
      booking.end_date < check.date || booking.date > check.end_date
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = params[:query].present? ? Lesson.search_by_name_and_description(params[:query]) : Lesson.all
  end

  def show
    @user = @lesson.user
    @bookings = @lesson.bookings
    @reviews = @lesson.reviews
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(params_allowed)
    @lesson.user = current_user
    if @lesson.save
      redirect_to lesson_path(@lesson)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @lesson.update(params_allowed)
      redirect_to lesson_path(@lesson)
    else
      render 'edit'
    end
  end

  def destroy
    @lesson.destroy
    redirect_to lessons_path
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def params_allowed
    params.require(:lesson).permit(:name, :description, :price, :duration, :category_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @categories = Category.all
  end

  def profile
    @user = current_user
    @bookings = current_user.bookings # user bookings of many mentor_lessons
    @lessons = current_user.lessons # lessons booked as a user
    if current_user.is_mentor
      @mentor_lesson = current_user.lesson # your lesson as a mentor
      if @mentor_bookings != nil
        @mentor_bookings = @mentor_lesson.bookings # mentor bookings of your lesson
      end
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(allowed_params)
    @review.booking_id = params[:booking_id]
    if @review.save
      redirect_to bookings_path
    else
      render 'new'
    end
  end

  private

  def allowed_params
    params.require(:review).permit(:title, :description, :rating, :booking_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="form-header">
  <h1 class='text-center'>Bookings Dashboard</h1>
</div>

<h2 class='text-center mt-5'><h2 class="name text-center"><%=current_user.name.capitalize %>,</h2></h2><h2 class="text-center"> you currently have <%= @bookings.count %> bookings</h2>

<div class="container mt-5 booking-index-container">
  <div class="d-flex flex-column">

    <% @bookings.each do |booking| %>
      <div class="card-product d-flex flex-row mt-4">
        <% if booking.user.photo.attached? %>
          <%= cl_image_tag booking.lesson.user.photo.key, height: 200, width: 200, crop: :fill, class:"img-border" %>
        <% else %>
          <img class="img-border" src="placeholder-profile.jpg" alt="placeholder">
        <% end %>
        <div class="card-product-infos">
          <h2 class="date"><%= booking.date.to_time.strftime('%A, %d %b %Y %l:%M %p')%></h2>
          <h2>Lesson booked:<h3><%= booking.lesson.name %></h3></h2>
          <h2>Mentor: <h3><%= booking.lesson.user.name.capitalize %></h3></h2> <%# mentor name  %>
          <h2>Description:<h3><%= booking.lesson.description %></h3></h2> <%# mentor lesson description  %>

          <% if booking.review != nil %>
            <div class="review p-4 border" style="width: 750px; margin-right: 18.5%; border-radius: 5px; background: rgba(37, 99, 56, 0.3); ">
              <div class="row">
                <div class="col-4">
                  <h2>Your review:<h3><%= booking.review.title %></h3></h2>
                  <% booking.review.rating.times do %>
                 <i class="fas fa-star text-warning"></i>
                <% end %>
                </div>
                <div class="col-8">
                 <h2>Review description:<h3><%= booking.review.description %></h3></h2>
                </div>
              </div>
            </div>
          <% elsif current_user == booking.user %> <%# if you are noy the mentor%>
            <%= link_to 'Leave a review', new_booking_review_path(booking), class: "btn form-btn booking-index"%>
          <% end %>
            <%= link_to 'Delete Booking', booking_path(booking), method: :delete,data: { confirm: "Are you sure you want to cancel this booking?" }, class: "btn form-btn booking-index" %>
        </div>
      </div>
    <% end %>

  </div>
<%= render 'shared/footer' %>
</div>

app/views/bookings/new.html.erb
<div class="container form-container bg-white ">
  <div class="book">
    <h5 class="form-title"><h1>Last step: book your lesson!</h1></h5>
  </div>
  <div class="c-flex">
    <div class=left>
      <div class="container">
     <h4 class="form-control booking">
      <p class="booking-title">You want to book:</p>
      <p class="booking-name"><%= @lesson.name %></p>
      <p class="booking-title">Lesson's mentor:</p>
      <p class="booking-name"><%= @lesson.user.name %></p>
    </h4>
    <%= simple_form_for  [@lesson, @booking] do |f| %>
              <%= f.input :date,
                          as: :string,
                          placeholder: 'Click here to choose a date',
                          label: false,
                          required: true,
                          input_html: {class: "datepicker"} %>
              <%= f.button :submit, "Book", class: "btn form-btn" %>
            <% end %>
          </div>
  </div>

  <div class=right>
    <div class="container mt-3">
    <h4 class="booking-title mb-4 ml-2">Check out who booked this lesson!</h4>
    <% @lesson.bookings.each do |booking| %>
    <div class="form-img-item item">
      <p><%= booking.user.name %> : <%= booking.date.to_time.strftime('%A, %d %b %Y %l:%M %p') %></p>
    </div>
    <% end %>
  </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mentup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if params["action"] != "home" %>
    <%= render 'shared/navbar' %>
    <% end  %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
  <footer>

  </footer>
</html>

app/views/lessons/_form.html.erb
<div class="container form-container bg-white ">
  <div class="c-flex">
    <div class=left>
      <div class="container">
<% if current_user.is_mentor %>
    <%= simple_form_for @lesson do |f| %>
      <%= f.input :name,
                  placeholder: 'Name your lesson',
                  label: false %>
      <%= f.input :description,
                  as: :text,
                  placeholder: 'Describe your lesson',
                  label: false %>
      <%= f.input :duration,
                  placeholder: 'How long is your lesson going to last?',
                  label: false,
                   as: :integer %>
      <%= f.input :price,
                  placeholder: 'What is the price?',
                  label: false,
                  as: :string %>
      <%= f.association :category,
                        placeholder: 'Pick a category for your lesson',
                        label: false,
                        as: :select %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn form-btn" %>
    <% end %>
<% else %>
  <div class="book">
    <h5 class="form-title"><h1 class="form-name">Start mentoring today!</h1></h5>
  </div>
  <div class="container">
  <h5 class="booking-name">Are you really good at something?<br> Share your best skill!</h5>
  <p class="booking-name">Becoming a mentor is the fastest way share your knowledge and capabilities.</p>
  <p class="booking-name">Manage dinamically your lesson and your bookings on Mentup.</p>
  <%= link_to 'Become a Mentor', edit_user_registration_path(current_user), class: "btn form-btn" %>
  </div>
<% end %>
</div>
</div>
  <div class="right">
    <div class="container right start" style="padding-top: 30px !important; padding-left: 110px;">
      <%= image_tag "hiclipart.com (foglia).png", style:'width: 17rem;'%>
    </div>
  </div>
</div>
</div>

app/views/lessons/edit.html.erb
<% if current_user.is_mentor %>
  <div class="book form-header" style="margin-left: 11.5%;">
    <h5 class="form-title"><h1>Update your lesson!</h1></h5>
  </div>
<% end %>

<%= render 'form' %>

app/views/lessons/index.html.erb
<div class="form-header">
<h1 class='text-center'>Find the perfect lesson for your needs</h1>
</div>
<br>
<div class="row d-flex justify-content-center">
  <div class="form-group col-md-12 d-flex justify-content-center">
    <%= form_tag lessons_path, method: :get do %>
      <div class="search-form-control form-group w-100 mt-3">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control search align-self-center mr-5",
        placeholder: "Find a lesson" %>
        <%= submit_tag "Search", class: "btn btn-flat" %>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-5">
  <div class="row">

  <% @lessons.each do |lesson|%>
    <div class="col-md-4">
      <div class="card-rounded my-2 mx-auto drop-shadow" style="width: 18rem; height: 22rem">

        <div class="card-body">
          <% if lesson.category.photo.attached? %>
            <div class="card-picture d-flex flex-column" style="background-image: linear-gradient(to bottom right, rgba(0,0,0,0.8),rgba(0,0,0,0.3)), url(<%= cl_image_path lesson.category.photo.key %>); height: 300; width: 400; crop: :fill">
          <% else %>
            <div class="card-picture d-flex flex-column" style="background-image: linear-gradient(to bottom right, rgba(0,0,0,0.8),rgba(0,0,0,0.3)), url(<%= image_path "mentup-verdone.png"%>); height: 300; width: 400; crop: :fill">
          <% end %>
          <p class="card-title text-white"><%= lesson.name %><p>
            </div>
          <div class="card-photos">

            <div class="card-profile-photo">
            <% if lesson.user.photo.attached? %>
              <%= cl_image_tag lesson.user.photo.key, height: 300, width: 400, crop: :fill, gravity: :face, class:"img-border avatar" %>
              <br>
            <% else %>
              <%= image_tag "placeholder-profile.jpg", class: "img-border", alt: "placeholder" %>
              <br>
            <% end %>
            </div>

            <div class="card-profile-name">
             <%= lesson.user.name %>
            </div>

          </div>

          <p class="lesson-description px-3" style="font-size: 0.8rem; height: 4rem;"><%= lesson.description %></p>
          <hr>
        </div>

          <div class="card-lesson-bottom">

            <div class="btn-see-lesson mt-5 ml-2">
              <%= link_to 'More info', lesson_path(lesson), class:'card-btn btn ' %>
            </div>

            <div class="lesson-price pt-5 mr-2">
              <small><%= lesson.price %>€ /</small>
              <small><%= lesson.duration %>h</small>
            </div>
          </div>

      </div>
    </div>
  <%end%>

  </div>
</div>



<%= render 'shared/footer' %>

app/views/lessons/new.html.erb
<% if current_user.is_mentor %>
  <div class="book" style="margin-left: 170px;">
    <h5 class="form-title">Hello, <%= current_user.name.capitalize %><h1 class="form-name">Create your lesson!</h1></h5>
  </div>
<% end %>


<%= render 'form' %>

app/views/lessons/show.html.erb
<div class="container-body mt-5">

  <div class="d-flex justify-content-around row" style="height: 80vh;">

    <div class="container-soraya border p-3 col-3 text-center ml-4">

      <div class="border-bottom m-4">
        <% if @user.photo.attached? %>
          <%= image_tag @user.photo, class: "avatar mb-4" %>
        <% else %>
          <%= image_tag "student.jpg", class: "avatar mb-4" %>
        <% end %>
        <h3><%= @user.name %></h3>
      </div>

      <div>
        <div class="w-90 p-5">
          <p> <em> <%= @user.bio %> </em></p>
        </div>
        <div class="w-90 mb-4 p-2">
          <% if @bookings.last %>
            <% if @bookings.last.review %>
              <h4> Last Rating for <%= @user.name %></h4>
              <p><%= @bookings.last.review.title %></p>
              <% @bookings.last.review.rating.times do %>
                <i class="fas fa-star text-warning"></i>
              <% end %>
            <% else %>
              <h4> <%= @user.name.capitalize %> has no reviews yet</h4>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container-soraya col-4 text-center d-flex flex-column">

      <div class="container-body rounded-sm flex-grow-1 mt-3 p-1">
        <h2><%= @lesson.name %></h2>
        <% if @lesson.photo.attached? %>
          <%= cl_image_tag @lesson.photo.key, class: 'img-show-lesson' %>
        <% else %>
          <%= image_tag "mentup-verdone.png"%>
        <% end %>
        <p class="p-3"> <%= @lesson.description %></p>
        <p> This lesson costs <%= @lesson.price %>€</p>
      <%= link_to "Book Lesson with this mentor", new_lesson_booking_path(@lesson), class: 'btn form-btn'%>

      </div>

    </div>


    <div class="container-soraya border rounded p-3 col-3 text-center mr-4">

      <div class="container-body" style="height: 15vh;">
        <% if @bookings %>
          <h5> This Mentor was already booked: </h5>
          <% @bookings.last(3).each do |booking| %>
          <p><%= booking.date.to_time.strftime('%A, %d %b %Y %l:%M %p')%></p>
          <% end %>
        <% else %>
          <h5>This mentor was never booked</h5>
        <% end %>
      </div>

      <div class="container-body rounded-sm flex-grow-1 mt-3" style="height: 60vh;">
        <h3>Last 3 reviews</h3>
        <% if @reviews.nil? %>
          <h5>There are no reviews</h5>
        <% else %>
            <% @reviews.last(3).each do |review| %>
              <div class="container-soraya rounded-sm m-2 p-2">
                <h5><%= review.title.capitalize %></h5>
                <p><%= review.description %></p>
                <% review.rating.times do %>
                  <i class="fas fa-star text-warning"></i>
                <% end %>
              </div>
            <% end %>
        <% end %>
      </div>

    </div>

  </div>
</div>
<%= render 'shared/footer' %>

app/views/pages/profile.html.erb
<div class="form-header">
  <h5 class="form-title text-center">Welcome<h1 class="form-name text-center">This is your profile!</h1>
</div>
<%= render 'shared/footer' %>
<div class="container-body">
  <div class="d-flex justify-content-around row" style="height: 80vh;">
    <div class="container-soraya border p-3 col-3 text-center ml-4" style="position: relative;">
      <div class="border-bottom m-4">
        <% if @user.photo.attached? %>
          <%= image_tag @user.photo, class: "avatar mb-4" %>
        <% else %>
          <%= image_tag "student.jpg", class: "avatar mb-4" %>
        <% end %>
        <h3><%= @user.name %></h3>
      </div>

      <div>
        <div class="w-90 p-5">
          <p><strong>  Bio </strong> </p>
          <p> <em> <%= @user.bio %> </em></p>
        </div>
        <%= link_to "Update your profile", edit_user_registration_path(@user), class: "btn form-btn profile-btn" %>
      </div>
    </div>

    <div class="container-soraya col-4 text-center d-flex flex-column" style="position: relative;">

      <% if @user.is_mentor%>
        <div class="container-body rounded-sm flex-grow-1 mt-3 p-1">
          <h2><%= @mentor_lesson.name %></h2>
          <%= cl_image_tag @mentor_lesson.photo.key, class: 'img-show-lesson' %>
          <p class="pt-2">Description</p>
          <p class="p-1"> <%= @mentor_lesson.description %></p>
          <p> Your lesson costs <%= @mentor_lesson.price %>€</p>
          <%= link_to "Update your lesson", edit_lesson_path(@mentor_lesson), class: "btn form-btn profile-btn" %>
        </div>
      <% else %>
        <%= image_tag "mentup-verdone.png", class: 'mt-5'%>
        <p><strong>Become a mentor with these 3 simple steps:</strong></p>
        <p>1- Change your profile settings to "Mentor"</p>
        <p>2- Create a lesson to teach others your best skill</p>
        <p>3- Recieve bookings and start your amazing mentoring journey</p>
        <%= link_to "Become a mentor and teach others to be Pros", edit_user_registration_path(@user), class: "btn form-btn profile-btn" %>
      <% end %>
    </div>


    <div class="container-soraya border rounded p-3 col-3 text-center mr-4" style="position: relative;">

      <div class="container-body" style="height: 15vh;">
        <% if @bookings %>
          <h5 class="mt-5 mb-3"> Your appointments: </h5>
          <% @bookings.last(5).each do |booking| %>
          <p><%= booking.date.to_time.strftime('%A, %d %b %Y %l:%M %p')%></p>
          <% end %>
          <%= link_to "All your bookings", bookings_path(@user), class: "btn form-btn mt-5 profile-btn" %>
        <% else %>
          <h5>You have no scheduled sessions</h5>
        <% end %>
      </div>

    </div>

</div>
<%= render 'shared/footer' %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="col-6 align-content-center">

  <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :rating, as: :integer %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer d-flex py-5 pl-5">
  <%= link_to "Home", root_path, class: "text-dark mx-2"  %>
  <%= link_to "Lessons", lessons_path, class: "text-dark mx-2" %>
  <%= link_to "Bookings", bookings_path, class: "text-dark mx-2" %>

  <% if user_signed_in? %>
    <% if current_user.lesson %>
      <%= link_to "Your lesson", lesson_path(current_user), class: "text-dark mx-2"  %>
    <% else %>
      <%= link_to "Create lesson", new_lesson_path, class: "text-dark mx-2" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_footerhome.html.erb
<div class="footer d-flex">
<%= link_to "Home", root_path, class: "text-white mx-2"  %>
<%= link_to "Lessons", lessons_path, class: "text-white mx-2" %>
<%= link_to "Bookings", bookings_path, class: "text-white mx-2" %>

<% if user_signed_in? %>
<% if current_user.lesson %>
<%= link_to "Your lesson", lesson_path(current_user), class: "text-white mx-2"  %>
<% else %>
<%= link_to "Create lesson", new_lesson_path, class: "text-white mx-2" %>
<% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "mentup-verdone.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto d-flex align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item-lesson">
          <% if current_user.is_mentor %>
          <%= link_to "Create a Lesson", new_lesson_path, class: "nav-link", id: "change-color" %>
          <% else %>
          <%= link_to "Become a Mentor", new_lesson_path, class: "nav-link", id: "change-color" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings", bookings_path, class: "nav-link", id: "change-color" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%=cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <% else %>
            <%= image_tag "https://img.pngio.com/smiling-man-png-high-quality-image-png-arts-png-smiling-man-550_410.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Your bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
          <%= link_to "Create a Lesson", new_user_session_path, class: "nav-link", id: "change-color" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" "btn btn-ghost sign-in-button", id: "change-color" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_transparent.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon transparent">
  <%= link_to root_path, class: "navbar-brand position-relative" do %>
    <%= image_tag "mentup-logo.png", class:'top-left', id:'logo-selector'%>
    <%= image_tag "mentup-verdone.png" , class:'invisible top-left'%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!--<div class="soraya"> > Categories </div>-->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto d-flex align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item-lesson">
          <% if current_user.is_mentor %>
          <%= link_to "Create a Lesson", new_lesson_path, class: "nav-link text-white", id: "change-color" %>
          <% else %>
          <%= link_to "Become a Mentor", new_lesson_path, class: "nav-link text-white", id: "change-color" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Bookings", bookings_path, class: "nav-link text-white", id: "change-color" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%=cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <% else %>
            <%= image_tag "https://img.pngio.com/smiling-man-png-high-quality-image-png-arts-png-smiling-man-550_410.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Your bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
          <%= link_to "Create a Lesson", new_user_session_path, class: "nav-link text-white", id: "change-color" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" "btn btn-ghost text-white sign-in-button", id: "change-color" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>